#!/bin/bash
function endian(){
    v=$1
    i=${#v}
    while [ $i -gt 0 ]; do
        i=$[$i-2]
        echo -n ${v:$i:2}
    done
    echo
}

if [ $# -eq 0 ]; then
    ext='ns3'
else
    ext=$1
fi
echo "Listing all $ext file start times in current directory:"
for file in ./*.$ext; do
    [[ -e "$file" ]] || continue
    # as per nsxdetails, this is probably not the smartest way of doing this...
    # but basically, we're reading in specific bits from the NSx file header and reversing to little-endian bytes
    filetype=$(xxd -p -l 8 $file | xxd -r -p)
    if [[ $filetype == "NEURALCD" ]] ; then
        year=$(endian $(xxd -p -l 2 -s 294 $file))
        month=$(endian $(xxd -p -l 2 -s 296 $file))
        day=$(endian $(xxd -p -l 2 -s 300 $file))
        hour=$(endian $(xxd -p -l 2 -s 302 $file))
        minute=$(endian $(xxd -p -l 2 -s 304 $file))
        second=$(endian $(xxd -p -l 2 -s 306 $file))
        printf -v year "%04d" $((16#$year))
        printf -v month "%02d" $((16#$month))
        printf -v day "%02d" $((16#$day))
        printf -v hour "%02d" $((16#$hour))
        printf -v minute "%02d" $((16#$minute))
        printf -v second "%02d" $((16#$second))
        dateformat=$(date -d "$year-$month-$day $hour:$minute:$second UTC")
        echo -e "\t$file:\t$dateformat"
    elif [[ $filetype == "NEURALSG" ]] ; then
        timeres=30000
        period=$(xxd -p -l 4 -s 24 $file)
        period=$(endian $period)
        fs=$(($timeres/$period))
        
        chancount=$(xxd -p -l 4 -s 28 $file)
        chancount=$(endian $chancount)
        chancount=$((16#$chancount))
        
        datastart=$((8+16+4+4+4*$chancount))
        totdatapoints=$(($filesize-$datastart))
        totdatapoints=$(($totdatapoints/($chancount*2)))
        
        totseconds=$(($totdatapoints/$fs))
        
        echo -e "\t$file:\t$totseconds seconds (NEURALSG)"
    fi
done